### ISSUE TITLE
[BUG] Whenever using save command the engine crashes

### ISSUE THREAD

**Issue by valina354** [Silverlan/pragma#112]
**General**
 - Pragma Version Latest main custom fork (https://github.com/Soft-Sprint-Studios/pragma-soft-sprint-studios1) The fork does not mess with saving code though so shouldnt be the issue

**Describe the bug**
The game crashes instantly after you run save, 

**To Reproduce**
1. Enter a map
2. Open Console
3. Type 'Save (something here any name)'

**Expected behavior**
The game will fully crash

**Screenshots**
![image](https://github.com/user-attachments/assets/7809e915-a4ce-453a-b294-9e3e405494ef)
![image](https://github.com/user-attachments/assets/22335b35-645f-4b34-8be5-8c854e9b9aca)

**Hardware (please complete the following information):**
 - OS: Windows 11
 - GPU: RTX 4060
 - GPU Driver version: 556.12

**Crashdump**
If Pragma has crashed and has generated a crashdump, please attach it to this issue.
[crashdump_2024-09-02_21-09-45.zip](https://github.com/user-attachments/files/16854643/crashdump_2024-09-02_21-09-45.zip)

**Comment by Silverlan** [comment]
Thanks for the report! Should be fixed in e31fadd1d5ed078638c464e41f0ea46ad45251b4 .

I'm not sure if the savegame system was ever completed though, so I don't know if it'll actually work.
