### ISSUE TITLE
[BUG] Trigger_changelevel crashes engine

### ISSUE THREAD

**Issue by valina354** [Silverlan/pragma#113]
**General**
 - Pragma Version Latest main custom fork (https://github.com/Soft-Sprint-Studios/pragma-soft-sprint-studios1) The fork does not mess with change level code though so shouldnt be the issue

**Describe the bug**
When i try to use trigger_changelevel to change maps the engine crashes, and the trigger_changelevel doesnt do anything

**To Reproduce**
1. enter a trigger_changelevel that is correctly set to load the next map
2. you should see the error as crash

**Expected behavior**
The Engine will crash

**Screenshots**
![image](https://github.com/user-attachments/assets/0efbfe8e-bcc5-4833-b1f4-ae8789780247)

**Hardware (please complete the following information):**
 - OS: Windows 11
 - GPU: RTX 4060
 - GPU Driver version: 556.12

**Crashdump**
If Pragma has crashed and has generated a crashdump, please attach it to this issue.
[crashdump_2024-09-08_15-22-43.zip](https://github.com/user-attachments/files/16922172/crashdump_2024-09-08_15-22-43.zip)

**Additional context**
VMF of the 2 maps:
[testchangelevel1.txt](https://github.com/user-attachments/files/16922173/testchangelevel1.txt)
[testchangelevel2.txt](https://github.com/user-attachments/files/16922174/testchangelevel2.txt)

the trigger_changelevel entity is from Pragma-HL

**Comment by Silverlan** [comment]
Thanks for the report! The crash should be fixed with de66ce2a8a79b542342473da5c57bb11b3c99884 .
