### ISSUE TITLE
Digital Signature

### ISSUE THREAD

**Issue by JohnnyG4** [Silverlan/pragma#114]
I formatted my PC recently (long story) and something that noticed after it, is that neither software wasn't opening and when i searched why, it seems that both softwares doesn't have something called "Digital Signature", with this i was thinking, what prevents from this to happen with other users that are trying the software too? So here's a suggestion for you to think about it in the future, i mean, Godot and Blender work fine and they have almost the same ideas.

**Comment by valina354** [comment]
Dont digital signatures cost money? thats what i know atleast

**Comment by JohnnyG4** [comment]
It's not something to do for now, i just think that can be useful in future, unless it's something monthly/yearly...but if/when the software gets big enough...

**Comment by Silverlan** [comment]
> I formatted my PC recently (long story) and something that noticed after it, is that neither software wasn't opening and when i searched why, it seems that both softwares doesn't have something called "Digital Signature", with this i was thinking, what prevents from this to happen with other users that are trying the software too? So here's a suggestion for you to think about it in the future, i mean, Godot and Blender work fine and they have almost the same ideas.

Can you please upload a screenshot of the error message?

**Comment by JohnnyG4** [comment]
![Captura de tela 2024-09-09 100042](https://github.com/user-attachments/assets/9dacb378-271f-43ac-b61a-125973097021)
I open the "execute anyway" (the one on the left) button, but it still don't open, it happens with both of them.
This might also be useful (Warning: it's in Brazilian Portuguese).
![Captura de tela 2024-09-09 100351](https://github.com/user-attachments/assets/f9e8409c-9157-463e-a5ba-37e76ed9ede6)
![Captura de tela 2024-09-09 100429](https://github.com/user-attachments/assets/c1dfc891-3068-49aa-952d-76fd4f106750)

**Comment by Silverlan** [comment]
> ![Captura de tela 2024-09-09 100042](https://private-user-images.githubusercontent.com/175258178/365659881-9dacb378-271f-43ac-b61a-125973097021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODc1NjEsIm5iZiI6MTcyNTg4NzI2MSwicGF0aCI6Ii8xNzUyNTgxNzgvMzY1NjU5ODgxLTlkYWNiMzc4LTI3MWYtNDNhYy1iNjFhLTEyNTk3MzA5NzAyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxMzA3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTg4OTdjYjQ2MTZiZjZjMDI2OTBkMmZiMzNhYTRkMDhhMGEyODIzZTc0MzU5N2UyZDhlODNmN2NmNmQ0ZWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y2GvldBBwfXqz303W6MLSwF7emXH2flqwZ7Zw_5Hcrc) I open the "execute anyway" (the one on the left) button, but it still don't open, it happens with both of them. This might also be useful (Warning: it's in Brazilian Portuguese). ![Captura de tela 2024-09-09 100351](https://private-user-images.githubusercontent.com/175258178/365661491-f9e8409c-9157-463e-a5ba-37e76ed9ede6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODc1NjEsIm5iZiI6MTcyNTg4NzI2MSwicGF0aCI6Ii8xNzUyNTgxNzgvMzY1NjYxNDkxLWY5ZTg0MDljLTkxNTctNDYzZS1hNWJhLTM3ZTc2ZWQ5ZWRlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxMzA3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODA0MWNiMTJhMjhkMjI4ZGNkYjMwNjY2YjA0YTc3NjAxYTlkMDdjY2FlYzNiMGFjYTIzN2IwNTBkNjkwYjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HsNmeVm9ZPrgwabZnYlheZoMntqQSNIwu9fcIjCfHVo) ![Captura de tela 2024-09-09 100429](https://private-user-images.githubusercontent.com/175258178/365661184-c1dfc891-3068-49aa-952d-76fd4f106750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODc1NjEsIm5iZiI6MTcyNTg4NzI2MSwicGF0aCI6Ii8xNzUyNTgxNzgvMzY1NjYxMTg0LWMxZGZjODkxLTMwNjgtNDlhYS05NTJkLTc2ZmQ0ZjEwNjc1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxMzA3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzExZWNjMDBkNThhNWUzYWUyMWQwZjZhM2MyMmFkYmMzZDZmNzZhYmMwNTViMDAyNjBiMjk0ZjdiYmM4NzM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wxBTIYHp08X28931NsbyPXLGddtmU7xnFzyRcbw4RIE)

That's a general thing that happens with Windows Defender sometimes. It can happen with pretty much any program, including Blender:
https://www.reddit.com/r/blender/comments/16yu3j7/aye_yo_why_is_windows_preventing_me_from_running/

It usually goes away by itself once more people have downloaded and run that particular version.
Not much I can do about it unfortunately, just click "More Info" -> "Run Anway".

**Comment by JohnnyG4** [comment]
I'll try, thanks for the patience.

**Comment by JohnnyG4** [comment]
Good news, it seems it was something related to the nightly builds, I've installed one of the more "concrete' builds recently and it worked just fine.
