### ISSUE TITLE
FileNotFoundError: [...] '/home/rasp/pragma/build/build_config.json'

### ISSUE THREAD

**Issue by raspimana** [Silverlan/pragma#25]
I have this script that runs the build script with the parameters of `--update 1 --with-pfm --with-all-pfm-modules --with-vr --no-sudo 1 --module pr_chromium:"https://github.com/Silverlan/pr_chromium"`. But, whenever I run it, it crashes with this error:
```
Traceback (most recent call last):
File "/home/rasp/pragma/build_scripts/build.py", line 85, in <module>
cfg = json.load(open(build_dir +"/build_config.json"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/rasp/pragma/build/build_config.json'
```
I'm using Garuda Linux. I've also tried re-cloning the repository.

**Comment by Silverlan** [comment]
Sorry for the late response, only just saw this issue.
The `--update 1` parameter should only be used after the script has already run successfully at least once. For the first time execution try:
`--with-pfm --with-all-pfm-modules --with-vr --no-sudo 1`

The chromium module is already included with the `--with-all-pfm-modules` parameter, so you don't need to add that either.

**Comment by raspimana** [comment]
Used the arguments that you provided, and then Pragma built successful . I'm gonna close this now.
