### ISSUE TITLE
Can't start Pragma: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Transform

### ISSUE THREAD

**Issue by raspimana** [Silverlan/pragma#28]
Whenever I try to start Pragma, I get this error: 

`Unable to load library 'lib/libclient.so': /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Transform`

It then quits after 5 seconds.
I'm using Garuda Linux. lib32-harfbuzz is the newest available.

**Comment by Silverlan** [comment]
Is this with the GitHub release, or the version you built yourself?

**Comment by raspimana** [comment]
> Is this with the GitHub release, or the version you built yourself?

The version I built myself. v105 works fine.

**Comment by raspimana** [comment]
I've found a workaround!

Clone [harfbuzz](https://github.com/harfbuzz/harfbuzz), and build it with `./autogen.sh && ./configure && make`.

Copy  `[harfbuzz repo]/src/.libs/libharfbuzz.so` to the root of the Pragma installation where the executable is.

Then, run Pragma with `LD_PRELOAD=libharfbuzz.so ./pragma`.

Tada! It starts. So is this an issue with Harfbuzz 6.0? Or maybe it's an issue with Arch's version of Harfbuzz?

**Comment by Silverlan** [comment]
Oh nice! I didn't know about that workaround.
The harfbuzz issue is unfortunately an infamous cyclic dependency between the freetype and harfbuzz libraries. I think it works as long as harfbuzz isn't installed on the system at all, not sure though, the behavior is somewhat inconsistent.
SlawekNowy has implemented a fix for the problem in [his fork](https://github.com/SlawekNowy/pragma) of Pragma, but that hasn't been merged yet. Once it's merged, it should work without the workaround.

I'll leave the issue open until then.

**Comment by Silverlan** [comment]
This should be fixed with the latest version, so I'm closing this for now.
