### ISSUE TITLE
Is it more convenient to use Pragma (as Filmmaker) or PFM?

### ISSUE THREAD

**Issue by gabrielgentien** [Silverlan/pragma#30]
As the title says, is one better than the other? Does one have less bugs and/or more functionality?

**Comment by Silverlan** [comment]
What do you mean? Pragma is the Engine, PFM is just an addon for it.

**Comment by gabrielgentien** [comment]
Then I have a pretty basic understanding problem I think. I thought that Pragma (in Filmmaker mode) was the same thing of PFM. What do you mean PFM is an addon? Pragma is an engine but also has a Filmmaker mode, and PFM is just a Filmmaker, is that what you're saying?

**Comment by Silverlan** [comment]
There is only one filmmaker, which is PFM.
PFM has it's [own repository](https://github.com/Silverlan/pfm) on GitHub, but it's included in the Pragma release. If you launch pfm.exe from the Pragma release, that's the same version as the pfm repository.

**Comment by gabrielgentien** [comment]
Perfect, understood. Thank you for your time!
