### ISSUE TITLE
Compiling a Sourcemod For Use With Pragma

### ISSUE THREAD

**Issue by Temmie19** [Silverlan/pragma#37]
Is this possible?

If so, how do you go about doing that?

**Comment by Temmie19** [comment]
Nooo I didn't want to add the bug label

**Comment by Silverlan** [comment]
Pragma doesn't use any Source Engine source code, so any mod for the source engine would be incompatible (i.e. no, it's not possible).

**Comment by Silverlan** [comment]
> Ohhh, okay. I guess I was confused, since you could mount Source games and import directly from Source Filmmaker. I thought you could run a Sourcemod through Pragma. I suppose that does make sense though

Nah, it's basically just limited to assets. I did start re-creating some Source Engine entities a while back, but did not get very far:
https://github.com/Silverlan/pragma_hl/tree/main/lua/entities/components
https://github.com/Silverlan/pragma_tf2/tree/main/lua/entities/components

But yeah, anything to do with scripting or modules would have to be re-created for Pragma unfortunately.
