### ISSUE TITLE
Resolve circular core dependencies

### ISSUE THREAD

**Issue by Silverlan** [Silverlan/pragma#9]
The core libraries (engine, shared, server, client, cengine) have several circular dependencies to each other that need to be resolved.
It should be:
**engine:** No dependencies to the others
**shared:** Dependent on engine
**server:** Dependent on shared and engine
**cengine:** Dependent on engine
**client:** Dependent on cengine, engine and shared

At the moment **shared** is also dependent on **server**, **engine** is dependent on **shared** and **cengine** is dependent on **client**. These need to be resolved!

**Comment by ivan-kulikov-dev** [comment]
shared_utils and mathutil also have a circular dependences. (when build with *_STATIC=OFF)

**Comment by ivan-kulikov-dev** [comment]
Maybe you need to move color from mathutils to shared_utils?
(and util::rgb_to_hsv, util::hsv_to_rgb)

**Comment by Silverlan** [comment]
Solved with 4c3e6b51daadc7abf007d9ba88da299f03628bd4
